Feature/keep alive
Wolkabout/WolkConnect-Cpp pull request #11
Opened 2018-03-29 09:06 UTC by milanzlicic

2018-03-29 11:43 UTC, svranesevic submitted a review, later dismissed

2018-03-30 07:56 UTC, svranesevic requested changes

2018-03-30 07:56 UTC, svranesevic commented on README.md
> +**Ping Mechanism:**
Custom keep alive mechanism

2018-03-30 07:56 UTC, svranesevic commented on README.md
> +WolkAbout C++ Connector by default uses ping mechanism to notify Wolkabout IOT Platform that device is still connected.
**WolkAbout IoT**

2018-03-30 07:56 UTC, svranesevic commented on README.md
> +Ping message is sent to Wolkabout IOT Platform every 10 minutes.
**WolkAbout IoT**

2018-03-30 07:56 UTC, svranesevic commented on README.md
> +    .withoutInternalPing() // Disable ping mechanism
withoutKeepAlive

2018-03-30 12:08 UTC, svranesevic submitted a review, later dismissed

2018-04-04 08:32 UTC, srdjastankovic approved these changes

2018-04-04 08:34 UTC, merged