JSON_PROTOCOL Support
Wolkabout/WolkConnect-Cpp pull request #36
Opened 2019-12-25 15:56 UTC by djesic

TODO: Update readme & sync with style guide

2019-12-27 15:17 UTC, djesic commented
Bug: Multi-value config invalid if first element is empty
Usability: Alter debug logging for messages received on `p2d/file_binary response`, stop from writing binary data to console!

2020-02-04 15:26 UTC, milanzlicic requested changes

2020-02-04 15:26 UTC, milanzlicic commented on src/service/DataService.h
> +    void addConfiguration(const std::vector<ConfigurationItem>& configuration);
Remove conf delimiters field if not used

2020-02-04 15:26 UTC, milanzlicic commented on src/Wolk.cpp
> +    addToCommandBuffer([=]() -> void { m_dataService->addSensorReading(reference, values, ",", rtc); });
If delimiter is removed than remove it here as well, otherwise leave it somewhere in sensor or device

2020-02-13 08:44 UTC, milanzlicic submitted a review, later dismissed

2020-06-26 14:02 UTC, closed without merging