Dfu
Wolkabout/WolkConnect-Cpp pull request #8
Opened 2018-01-30 14:59 UTC by milanzlicic

2018-01-31 14:12 UTC, svranesevic requested changes

2018-01-31 14:12 UTC, svranesevic commented on LicenceHeader
> + * Copyright 2017 WolkAbout Technology s.r.o.
Update year - 2018

2018-01-31 14:12 UTC, svranesevic commented on LicenceHeader
> + * Copyright 2017 WolkAbout Technology s.r.o.
All copyright instances

2018-01-31 14:12 UTC, svranesevic commented on src/FileHandler.cpp
> +FileHandler::StatusCode FileHandler::validateFile(const ByteArray& fileHash)
How about:
```cpp
FileHandler::StatusCode FileHandler::validateFile(const ByteArray& fileHash)
{
    if (fileHash != ByteUtils::hashSHA256(m_currentPacketData))
    {
        FileHandler::StatusCode::FILE_HASH_NOT_VALID;
    }

    return return FileHandler::StatusCode::OK;
}
```

* Reduces nesting
* Simplifies flow - Early exit on invalid hash

2018-01-31 14:12 UTC, svranesevic commented on src/FileHandler.cpp
> +FileHandler::StatusCode FileHandler::saveFile(const std::string& filePath)
Same as 'FileHandler::StatusCode FileHandler::validateFile'

2018-01-31 14:12 UTC, svranesevic commented on src/FileHandler.h
> +	FileHandler::StatusCode saveFile(const std::string& filePath);
FileHandler::StatusCode saveFile(const std::string& filePath) const; ?

2018-01-31 14:12 UTC, svranesevic commented on src/FileHandler.h
> +	FileHandler::StatusCode validateFile(const ByteArray& fileHash);
FileHandler::StatusCode validateFile(const ByteArray& fileHash) const; ?

2018-01-31 14:12 UTC, svranesevic commented on src/InboundMessageHandler.cpp
> +	std::cout << "Message received: " << topic << ", " << message << std::endl;
Remove stale std::cout, or comment out until logging functionality is added

2018-01-31 14:12 UTC, svranesevic commented on src/InboundMessageHandler.cpp
> +			BinaryData data{ByteUtils::toByteArray(message)};
What if received data can not fit on stack, what about placing this on heap ?

2018-01-31 14:12 UTC, svranesevic commented on src/InboundMessageHandler.h
> +	static const constexpr char* ACTUATION_REQUEST_TOPIC_ROOT = "actuators/commands/";
Note: 'constexpr' marks entity as constant as well, hence 'const constexpr' is redundant

2018-01-31 14:12 UTC, svranesevic commented on src/Wolk.cpp
> +		if(m_connectivityService->connect())
Invert condition to reduce nesting

```cpp
if (!m_connectivityService->connect()) {
    return;
}
```

2018-01-31 14:12 UTC, svranesevic commented on src/Wolk.cpp
> +			// Log error
// TODO: Log error
Here and on every other place that has placeholder for logger, much easier to find these when 'TODO' tag exists

2018-01-31 14:12 UTC, svranesevic commented on src/WolkBuilder.cpp
> +const unsigned WolkBuilder::MAX_BINARY_CHUNK_SIZE = 131072;
This should be configurable

2018-01-31 14:12 UTC, svranesevic commented on src/WolkBuilder.cpp
> +	inboundMessageHandler->setActuatorCommandHandler([&](const ActuatorCommand& actuatorCommand) -> void {
Any specific reason for using lambda handlers ? (Just wondering)

2018-01-31 14:12 UTC, svranesevic commented on src/WolkBuilder.h
> +#include <stdint.h>
```cpp
#include <cstdint>
```

2018-01-31 14:12 UTC, svranesevic commented on src/connectivity/json/JsonDtoParser.cpp
> +        else
Redundant 'else'

2018-01-31 14:12 UTC, svranesevic commented on src/connectivity/json/JsonDtoParser.cpp
> +			else
Redundant else

2018-01-31 14:12 UTC, svranesevic commented on src/connectivity/json/JsonDtoParser.cpp
> +			else
Redundant else

2018-01-31 14:12 UTC, svranesevic commented on src/connectivity/json/JsonDtoParser.cpp
> +			else
Redundant else

2018-01-31 14:12 UTC, svranesevic commented on src/connectivity/json/JsonDtoParser.cpp
> +			else
Redundant else

2018-01-31 14:12 UTC, svranesevic commented on src/connectivity/mqtt/MqttConnectivityService.cpp
> +			auto topics = handler->getTopics();
Inline, or
```cpp
const auto& topics = handler->getTopics();
```

2018-01-31 14:12 UTC, svranesevic commented on src/connectivity/mqtt/PahoMqttClient.cpp
> +	std::lock_guard<std::mutex> guard(m_mutex);
NOTE: Verify connector with thread sanitizer

2018-01-31 14:12 UTC, svranesevic commented on src/model/BinaryData.h
> +	static const short SHA_256_HASH_BYTE_LENGTH = 32;
Is 'public' visibility really needed here?

2018-01-31 14:12 UTC, svranesevic commented on LicenceHeader
> + * Copyright 2017 WolkAbout Technology s.r.o.
HINT:
```shell
grep -rl . -e "Copyright 2017 WolkAbout Technology s.r.o." | xargs sed -i 's/2017/2018/g'
```

2018-01-31 14:12 UTC, svranesevic commented on src/model/FilePacketRequest.h
> +#include <string>
Missing
```cpp
#include <cstdint>
```
for 'uint_fast64_t' used on line 36

2018-01-31 14:12 UTC, svranesevic commented on src/model/FirmwareUpdateCommand.h
> +#include <string>
Missing
```cpp
#include <cstdint>
```
for 'uint_fast64_t' used on line 48

2018-01-31 14:12 UTC, svranesevic commented on src/model/FirmwareUpdateCommand.h
> +	WolkOptional<std::string> getName() const;
```cpp
const WolkOptional<std::string>&
```
Here, and on subsequent getters

2018-01-31 14:12 UTC, svranesevic commented on src/model/WolkOptional.h
> +        static_assert(std::is_default_constructible<T>::value, "Type doesn't have default constructor");
"Wrapped type must be default constructible"

2018-01-31 14:12 UTC, svranesevic commented on src/service/FileDownloadService.cpp
> +	if(m_retryCount == FileDownloadService::MAX_RETRY_COUNT)
Reduce nesting with early exit, eg.

```cpp
void FileDownloadService::packetFailed()
{
    if(m_retryCount == FileDownloadService::MAX_RETRY_COUNT)
    {
        abort();
        if(m_currentOnFailCallback)
        {
            m_currentOnFailCallback(WolkaboutFileDownloader::Error::RETRY_COUNT_EXCEEDED);
        }
        return;
    }

    requestPacket(m_currentPacketIndex, m_currentPacketSize);
}
```

2018-01-31 14:12 UTC, svranesevic commented on src/service/FileDownloadService.cpp
> +		auto count = static_cast<double>(fileSize) / (m_service.m_maxPacketSize - (2 * BinaryData::SHA_256_HASH_BYTE_LENGTH));
```cpp
const auto count = static_cast<double>(fileSize) / (m_service.m_maxPacketSize - (2 * BinaryData::SHA_256_HASH_BYTE_LENGTH));
```

2018-01-31 14:12 UTC, svranesevic commented on src/model/WolkOptional.h
> +    bool null() const { return m_null; }
Use bool conversion operator instead
```cpp
operator bool() const
{
    return !m_null;
}
```

Allows for cleaner code where used, eg.
```cpp
if (m_optional)
{
   ...
}
```
instead of 
```cpp
if (!m_optional.null())
{
   ...
}
```

2018-01-31 14:12 UTC, svranesevic commented on src/service/FileDownloadService.cpp
> +	auto result = m_service.m_fileHandler->handleData(binaryData);
```cpp
const auto result = ...
```

2018-01-31 14:12 UTC, svranesevic commented on src/service/FileDownloadService.cpp
> +				auto validationResult = m_service.m_fileHandler->validateFile(m_service.m_currentFileHash);
```cpp
const auto validationResult = ...
```

2018-01-31 14:12 UTC, svranesevic commented on src/service/FileDownloadService.cpp
> +						auto saveResult = m_service.m_fileHandler->saveFile(filePath);
```cpp
const auto saveResult = ...
```

2018-01-31 14:12 UTC, svranesevic commented on src/service/FileDownloadService.h
> +#include <stdint.h>
```cpp
#include <cstdint>
```

2018-01-31 14:12 UTC, svranesevic commented on src/service/FirmwareUpdateService.h
> +
```cpp
#include <cstdint>
```

2018-01-31 14:12 UTC, svranesevic commented on src/service/FirmwareUpdateService.cpp
> +
```cpp
#include <cstdint>
```

2018-01-31 14:12 UTC, svranesevic commented on src/service/FirmwareUpdateService.cpp
> +				auto autoInstall = firmwareUpdateCommand.getAutoInstall();
const

2018-01-31 14:12 UTC, svranesevic commented on src/service/FirmwareUpdateService.cpp
> +				auto byteHash = ByteUtils::toByteArray(StringUtils::base64Decode(hash));
const

2018-01-31 14:12 UTC, svranesevic commented on src/service/FirmwareUpdateService.cpp
> +			auto url = firmwareUpdateCommand.getUrl();
const

2018-01-31 14:12 UTC, svranesevic commented on src/service/FirmwareUpdateService.cpp
> +				auto autoInstall = firmwareUpdateCommand.getAutoInstall();
const

2018-01-31 14:12 UTC, svranesevic commented on src/service/FirmwareUpdateService.cpp
> +				// log error
// TODO: Log error

2018-01-31 14:12 UTC, svranesevic commented on src/service/FirmwareUpdateService.cpp
> +					// log error
// TODO: Log error

2018-01-31 14:12 UTC, svranesevic commented on src/service/FirmwareUpdateService.cpp
> +					// log error
// TODO: Log error

2018-01-31 14:12 UTC, svranesevic commented on src/service/WolkaboutFileDownloader.h
> +
```cpp
#include <cstdint>
```

2018-01-31 14:12 UTC, svranesevic commented on src/utilities/ByteUtils.cpp
> +	for(auto it = data.begin(); it != data.end(); ++it)
Range based for-loop or use constant iterators (cbegin, cend)

2018-01-31 14:12 UTC, svranesevic commented on src/utilities/ByteUtils.h
> +using ByteArray = std::vector<uint8_t>;
ByteVector is more appropriate here, no ?

2018-01-31 14:12 UTC, svranesevic commented on src/utilities/ByteUtils.h
> +using ByteArray = std::vector<uint8_t>;
Also,
use already aliased 'Byte', eg.
```cpp
using ByteVector = std::vector<Byte>
```

2018-01-31 14:12 UTC, svranesevic commented on src/utilities/Timer.cpp
> +		std::unique_lock<std::mutex> lock{m_lock};
Use 'std::guard_lock' for RAII, or use 'std::unique_lock' with 'std::unique_lock::lock' and 'std::unique_lock::unlock'

2018-01-31 14:12 UTC, svranesevic commented on src/utilities/Timer.h
> +
```cpp
#include <memory>
```

2018-01-31 14:16 UTC, svranesevic requested changes

2018-01-31 14:16 UTC, svranesevic commented on src/service/FirmwareUpdateService.cpp
> +			m_service.clear();
Refactor 'clear' to 'reset' ?

2018-01-31 14:16 UTC, svranesevic commented on src/service/FirmwareUpdateService.cpp
> +				// log error
// TODO: Log error

2018-02-01 12:40 UTC, milanzlicic commented on src/service/FirmwareUpdateService.cpp
> +
Will be already included in .h

2018-02-01 14:39 UTC, milanzlicic commented on src/InboundMessageHandler.h
> +	static const constexpr char* ACTUATION_REQUEST_TOPIC_ROOT = "actuators/commands/";
The constexpr tells that the value of char pointer can be evaluated at compile time, but the const is needed to tell that the values at the address the pointer is pointing to will not change. Won't compile without const

2018-02-01 14:40 UTC, milanzlicic commented on src/model/BinaryData.h
> +	static const short SHA_256_HASH_BYTE_LENGTH = 32;
Moved to ByteUtils as it is used in a few places

2018-02-01 14:40 UTC, milanzlicic commented on src/model/WolkOptional.h
> +    bool null() const { return m_null; }
Thought of it, but that would conflict with operator T() if T is bool

2018-02-01 14:56 UTC, svranesevic commented on src/model/WolkOptional.h
> +    bool null() const { return m_null; }
What about mimicking std::optional (http://en.cppreference.com/w/cpp/utility/optional/value)

2018-02-01 15:39 UTC, milanzlicic commented on src/InboundMessageHandler.cpp
> +			BinaryData data{ByteUtils::toByteArray(message)};
Will be fixed if it becomes a problem

2018-02-01 15:42 UTC, milanzlicic commented on src/model/WolkOptional.h
> +    bool null() const { return m_null; }
Good idea, may implement it in a the future

2018-02-02 12:18 UTC, svranesevic approved these changes

2018-02-02 12:19 UTC, svranesevic requested changes
Update README with firmware update section

2018-02-02 15:09 UTC, svranesevic approved these changes

2018-02-05 09:05 UTC, merged